# Azure Pipelines file, see https://aka.ms/yaml

# Enable builds on all branches
trigger:
  # Build every commit as our release process relies on
  # the release process being built alone.
  batch: false
  branches:
    include:
      - master

# Enable PR triggers that target the master branch
pr:
  autoCancel: true # cancel previous builds on push
  branches:
    include:
      - master

jobs:
  - job: windows
    timeoutInMinutes: 360
    pool:
      # vmImage: 'vs2017-win2016'
      name: windows-pool
    steps:
      - template: ci/build-windows.yml

